# Generated by Django 6.0.2 on 2026-04-19 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_voter_id', models.CharField(blank=True, max_length=30)),
                ('aadhaar_last4', models.CharField(blank=True, help_text='Last 4 digits only', max_length=4)),
                ('full_name_on_card', models.CharField(blank=True, max_length=150)),
                ('dob_on_card', models.DateField(blank=True, null=True)),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='voter_cards/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voter_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voter_verifications',
            },
        ),
    ]
