# Generated by Django 6.0.4 on 2026-05-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=30)),
                ('aadhaar_last4', models.CharField(help_text='Last 4 digits of Aadhaar', max_length=4)),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('village', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending_village_admin', 'Pending Village Admin'), ('pending_voter_admin', 'Pending Voter Administrative'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_village_admin', max_length=30)),
                ('ai_score', models.IntegerField(default=0, help_text='Genuineness score 0-100')),
                ('ai_details', models.JSONField(default=dict, help_text='Breakdown of AI checks')),
                ('village_admin_notes', models.TextField(blank=True)),
                ('voter_admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forwarded_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registration_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='registratio_status_ac51a3_idx'), models.Index(fields=['voter_id'], name='registratio_voter_i_bca000_idx'), models.Index(fields=['email'], name='registratio_email_b0b6d2_idx')],
            },
        ),
    ]
