# Generated by Django 6.0.4 on 2026-05-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
