# Generated by Django 6.0.4 on 2026-05-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_alter_candidate_party_alter_candidate_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
