# Generated by Django 6.0.4 on 2026-04-18 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote_hash', models.CharField(max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.election')),
            ],
            options={
                'db_table': 'votes',
                'indexes': [models.Index(fields=['election', 'candidate'], name='votes_electio_8024c7_idx'), models.Index(fields=['vote_hash'], name='votes_vote_ha_638aac_idx')],
            },
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='elections.election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vote_records',
                'indexes': [models.Index(fields=['user', 'election'], name='vote_record_user_id_fb909f_idx')],
                'unique_together': {('user', 'election')},
            },
        ),
    ]
